#pragma once

#define CODE_SEGMENT_SELECTOR 0x08
#define VIDEO_MEMORY_ADDR 0xb8000

#define SCREEN_WIDTH (80 * 2)
#define SCREEN_HEIGHT 25
#define SCREEN_SIZE (SCREEN_WIDTH * SCREEN_HEIGHT)

#define VIDEO_MEMORY_ATTR 0x07
